image: openjdk:9

pipelines:
  default:
    - step:
        caches:
          - gradle
          - node
        script:
          - bash ./gradlew build
          - apt-get update
          - apt-get install -y zip
          - zip -r template.zip .
