image: openjdk:9

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew build
    - step:
        script:
          - bash zip -r build.zip ./build
