image: openjdk:9

pipelines:
  default:
    - step:
        caches:
          - gradle
          - node
        script:
          - bash ./gradlew build
          - apt-get update
          - apt-get install -y rsync
          - mkdir -p ./template && rsync -a . ./template --exclude .hg --exclude .gradle --exclude build --exclude node_modules
          - export ARTIFACT_NAME="template-version-$BITBUCKET_BUILD_NUMBER.tar.gz"
          - cd template && tar -zcf ../$ARTIFACT_NAME * && cd -
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@$ARTIFACT_NAME
