image: openjdk:9

pipelines:
  default:
    - step:
        caches:
          - gradle
          - node
        script:
          - bash ./gradlew build
          - apt-get update
          - apt-get install -y zip
          - mkdir -p ./template && rsync -a . ./template --exclude .hg --exclude .gradle --exclude build --exclude node_modules
          - cd template && tar -zcf ../template.tar.gz * && cd -
